<?xml version="1.0" encoding="utf-8"?><Database Name="GTSdb" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LENGUYEN\SQLEXPRESS;Initial Catalog=GTSdb;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GTSdbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CoInfo" Member="CoInfos">
    <Type Name="CoInfo">
      <Column Name="InfoId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastUpdt" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRoles" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="Uid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Role_UserRole" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
      <Association Name="User_UserRole" Member="User" ThisKey="Uid" OtherKey="Uid" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contacts" Member="Contacts">
    <Type Name="Contact">
      <Column Name="ContactId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Contents" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ContactDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsSolved" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastUpdt" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="CountryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CountryNm" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Country_Location" Member="Locations" ThisKey="CountryId" OtherKey="CountryId" Type="Location" />
    </Type>
  </Table>
  <Table Name="dbo.Events" Member="Events">
    <Type Name="Event">
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventNm" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FromDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LocaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Location_Event" Member="Location" ThisKey="LocaId" OtherKey="LocaId" Type="Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Hotel" Member="Hotels">
    <Type Name="Hotel">
      <Column Name="HotelId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HotelNm" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Star" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Price" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PicPath1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PicPath2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LocaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Location_Hotel" Member="Location" ThisKey="LocaId" OtherKey="LocaId" Type="Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Location" Member="Locations">
    <Type Name="Location">
      <Column Name="LocaId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LocaNm" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Location_Event" Member="Events" ThisKey="LocaId" OtherKey="LocaId" Type="Event" />
      <Association Name="Location_Hotel" Member="Hotels" ThisKey="LocaId" OtherKey="LocaId" Type="Hotel" />
      <Association Name="Location_Tour" Member="Tours" ThisKey="LocaId" OtherKey="LocaId" Type="Tour" />
      <Association Name="Country_Location" Member="Country" ThisKey="CountryId" OtherKey="CountryId" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleNm" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="Role_UserRole" Member="UserRoles" ThisKey="RoleId" OtherKey="RoleId" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.TourGroups" Member="TourGroups">
    <Type Name="TourGroup">
      <Column Name="TourGroupId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TourGroupNm" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TourHotel" Member="TourHotels">
    <Type Name="TourHotel">
      <Column Name="TourId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HotelId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TourKinds" Member="TourKinds">
    <Type Name="TourKind">
      <Column Name="TourKindId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TourKindNm" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TourGroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TourKind_Tours_TourKind" Member="Tours_TourKinds" ThisKey="TourKindId" OtherKey="TourKindId" Type="Tours_TourKind" />
    </Type>
  </Table>
  <Table Name="dbo.TourReg" Member="TourRegs">
    <Type Name="TourReg">
      <Column Name="TourRegId" Type="System.String" DbType="Char(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlaceNm" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Hotel" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Adult" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Child" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TourGuide" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Trans" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUpdt" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsSolved" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tours" Member="Tours">
    <Type Name="Tour">
      <Column Name="TourId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TourNm" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DescReview" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LocaId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HotelId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tour_Tours_TourKind" Member="Tours_TourKinds" ThisKey="TourId" OtherKey="TourId" Type="Tours_TourKind" />
      <Association Name="Location_Tour" Member="Location" ThisKey="LocaId" OtherKey="LocaId" Type="Location" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tours_TourKinds" Member="Tours_TourKinds">
    <Type Name="Tours_TourKind">
      <Column Name="TourId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TourKindId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="TourKind_Tours_TourKind" Member="TourKind" ThisKey="TourKindId" OtherKey="TourKindId" Type="TourKind" IsForeignKey="true" />
      <Association Name="Tour_Tours_TourKind" Member="Tour" ThisKey="TourId" OtherKey="TourId" Type="Tour" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Uid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usnm" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Pwd" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullNm" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sex" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HomePhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastUpdt" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="User_UserRole" Member="UserRoles" ThisKey="Uid" OtherKey="Uid" Type="UserRole" />
    </Type>
  </Table>
</Database>